#!/usr/bin/env bash


function test {
    $(vessel bin)/moc -r $(vessel sources 2> /dev/null) src/Date.test.mo
}

function check {
    for i in src/*.mo ; do $(vessel bin)/moc $(vessel sources 2>/dev/null) --check $i ; done
}


case $1 in
  "test")   test;;     # ./run test
  "check")  check;;    # ./run check
  *)        test;;     # ./run
esac
